// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfrkEB9RvkYSNEQA3Ftf9Ky9eGgURPZCE',
    appId: '1:1067984951479:web:f61fbab598c1a8a1585532',
    messagingSenderId: '1067984951479',
    projectId: 'reci-7da8b',
    authDomain: 'reci-7da8b.firebaseapp.com',
    storageBucket: 'reci-7da8b.appspot.com',
    measurementId: 'G-XSNNZ8QSMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVzz8YMi0DUAw8GJjlx_iTwmRnpnrl3F4',
    appId: '1:1067984951479:android:211e74091ce16b1f585532',
    messagingSenderId: '1067984951479',
    projectId: 'reci-7da8b',
    storageBucket: 'reci-7da8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASUgcmxkO781Q_AcEASOBdasCGanZgXJ0',
    appId: '1:1067984951479:ios:ce8f377c8602f33b585532',
    messagingSenderId: '1067984951479',
    projectId: 'reci-7da8b',
    storageBucket: 'reci-7da8b.appspot.com',
    iosClientId: '1067984951479-hocmq0mi3h2r5dh221gg76nf7k5n91tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASUgcmxkO781Q_AcEASOBdasCGanZgXJ0',
    appId: '1:1067984951479:ios:ce8f377c8602f33b585532',
    messagingSenderId: '1067984951479',
    projectId: 'reci-7da8b',
    storageBucket: 'reci-7da8b.appspot.com',
    iosClientId: '1067984951479-hocmq0mi3h2r5dh221gg76nf7k5n91tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipe',
  );
}
