name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Firebase App Distribution Action
        uses: ./
        with:
          app_id: ${{secrets.FIREBASE_APP_ID}}
          firebase_token: ${{secrets.FIREBASE_TOKEN}}
          app_file: app-release-ac-signed.apk
          tester_groups: maintainers